language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

os:
  - linux
  - osx

before_script:
  - wget http://browscap.org/stream?q=Full_PHP_BrowsCapINI -O /tmp/browscap.ini
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "5.5" ] || [ "`phpenv version-name`" == "5.6" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ] && [ "`phpenv version-name`" != "hhvm-nightly" ]; then echo 'browscap = "/tmp/browscap.ini"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update
  - if [ "`phpenv version-name`" != "5.3" ]; then composer require --no-update browscap/browscap:*@dev; fi
  - composer install --dev -o --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

