language: php
sudo: false

php:
  - 7.1

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $TRAVIS_BUILD_DIR/resources
    - $HOME/.composer/cache

stages:
  - composer validate
  - check coding style
  - static code analysis
  - test
  - test with coverage
  - compare results

before_install:
  - .travis-scripts/cache-browscap.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv $COMPOSER_FLAGS

script: vendor/bin/phpunit -c phpunit.xml.dist --no-coverage --colors --verbose --exclude-group compare

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - stage: test with coverage
      php: 7.1
      env:
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      before_install:
        - .travis-scripts/cache-browscap.sh
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
      script: vendor/bin/phpunit -c phpunit.xml.dist --colors --verbose --exclude-group compare --coverage-text --coverage-clover=coverage.clover
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f coverage.clover -F phpunit

    - stage: composer validate
      php: 7.1
      env: COMPOSER_FLAGS=""
      before_install:
        - phpenv config-rm xdebug.ini || echo "xdebug not available"
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      install: skip
      script: composer validate --strict

    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: php -n -d memory_limit=768M vendor/bin/php-cs-fixer fix --dry-run -vv

    - stage: static code analysis
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src tests

    - stage: compare results
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit -c phpunit.xml.dist --colors --verbose --no-coverage --group compare

